### ISSUE TITLE
Missing pre-requisites section in README

### ISSUE THREAD

**Issue by ramgopaltanikella** [oracle/coherence-helidon-sockshop-sample#22]
The pre-requisites section in README (https://github.com/oracle/coherence-helidon-sockshop-sample#pre-requisites) is missing. I am planning to try out the sample on my local m/c.

**Comment by tmiddlet2666** [comment]
Hi @ramgopaltanikella 
Thanks for your issue.

I'll be fixing this up, but in the meantime you need at least
1. Latest version of `kubectl` available from https://kubernetes.io/docs/tasks/tools/.
2. Docker or Rancher 
3. A remote or local Kubernetes cluster
4. Maven 3.8+ and JDK 11+

Let me know if you have any issues with the demo
